import express from 'express'
import PDFDocument from 'pdfkit'
import { pool } from '../db/pool.js'
import { requireAuth } from '../middleware/auth.js'

const router = express.Router()

router.post('/', requireAuth, async (req, res) => {
  try {
    const { userId } = req.auth
    const { month, signature } = req.body
    console.log('export body:', { month: month || 'none', hasSig: !!signature })

    const proResult = await pool.query(
      'SELECT * FROM professionals WHERE clerk_user_id = $1',
      [userId]
    )
    if (proResult.rows.length === 0) return res.status(404).json({ error: 'Professional record not found' })
    const pro = proResult.rows[0]

    let dateFilter = ''
    let queryParams = [pro.id]
    if (month) {
      dateFilter = `AND DATE_TRUNC('month', entry_date) = DATE_TRUNC('month', $2::date)`
      queryParams.push(`${month}-01`)
    }

    const entriesResult = await pool.query(
      `SELECT * FROM fieldwork_entries WHERE professional_id = $1 ${dateFilter} ORDER BY entry_date ASC, start_time ASC`,
      queryParams
    )
    const entries = entriesResult.rows

    const totalHours = entries.reduce((sum, e) => sum + parseFloat(e.hours || 0), 0)
    const supervisedHours = entries.filter(e => e.supervised).reduce((sum, e) => sum + parseFloat(e.hours || 0), 0)
    const unrestrictedHours = entries.filter(e => e.experience_type === 'unrestricted').reduce((sum, e) => sum + parseFloat(e.hours || 0), 0)
    const restrictedHours = entries.filter(e => e.experience_type === 'restricted').reduce((sum, e) => sum + parseFloat(e.hours || 0), 0)
    const supervisionPct = totalHours > 0 ? (supervisedHours / totalHours) * 100 : 0
    const monthLabel = month ? new Date(`${month}-01`).toLocaleDateString('en-US', { month: 'long', year: 'numeric' }) : 'All Time'

    const doc = new PDFDocument({ margin: 50, size: 'LETTER', layout: 'landscape' })
    res.setHeader('Content-Type', 'application/pdf')
    res.setHeader('Content-Disposition', `attachment; filename="supervisd-hours-${month || 'all'}.pdf"`)
    doc.pipe(res)

    const PAGE_W = doc.page.width
    const MARGIN = 50
    const CONTENT_W = PAGE_W - MARGIN * 2

    doc.rect(MARGIN, MARGIN, CONTENT_W, 4).fill('#1A7A50')
    doc.y = MARGIN + 16
    doc.font('Helvetica-Bold').fontSize(18).fillColor('#0F2018').text('BACB Fieldwork Experience Verification', MARGIN, doc.y)
    doc.font('Helvetica').fontSize(10).fillColor('#5A7A65').text(`Generated by Supervisd  ·  ${new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}`, MARGIN)
    doc.moveDown(1)

    const infoY = doc.y
    const col1 = MARGIN, col2 = MARGIN + 240, col3 = MARGIN + 460

    doc.font('Helvetica-Bold').fontSize(8).fillColor('#5A7A65').text('PROFESSIONAL NAME', col1, infoY)
    doc.font('Helvetica').fontSize(11).fillColor('#0F2018').text(pro.full_name || '—', col1, infoY + 12)
    doc.font('Helvetica-Bold').fontSize(8).fillColor('#5A7A65').text('BACB PID', col2, infoY)
    doc.font('Helvetica').fontSize(11).fillColor('#0F2018').text(pro.bacb_pid || '—', col2, infoY + 12)
    doc.font('Helvetica-Bold').fontSize(8).fillColor('#5A7A65').text('CREDENTIAL #', col3, infoY)
    doc.font('Helvetica').fontSize(11).fillColor('#0F2018').text(pro.credential_number || '—', col3, infoY + 12)

    const infoY2 = infoY + 42
    doc.font('Helvetica-Bold').fontSize(8).fillColor('#5A7A65').text('AGENCY', col1, infoY2)
    doc.font('Helvetica').fontSize(11).fillColor('#0F2018').text(pro.agency_name || '—', col1, infoY2 + 12)
    doc.font('Helvetica-Bold').fontSize(8).fillColor('#5A7A65').text('ROLE', col2, infoY2)
    doc.font('Helvetica').fontSize(11).fillColor('#0F2018').text((pro.role || '').toUpperCase(), col2, infoY2 + 12)
    doc.font('Helvetica-Bold').fontSize(8).fillColor('#5A7A65').text('PERIOD', col3, infoY2)
    doc.font('Helvetica').fontSize(11).fillColor('#0F2018').text(monthLabel, col3, infoY2 + 12)

    doc.y = infoY2 + 32
    doc.rect(MARGIN, doc.y, CONTENT_W, 1).fill('#D8E4DC')
    doc.moveDown(0.8)

    const statsY = doc.y
    const statCols = [col1, col1+130, col1+260, col1+390, col1+520]
    const stats = [['TOTAL HOURS', totalHours.toFixed(1)], ['UNRESTRICTED', unrestrictedHours.toFixed(1)], ['RESTRICTED', restrictedHours.toFixed(1)], ['SUPERVISED', supervisedHours.toFixed(1)], ['SUPERVISION %', supervisionPct.toFixed(1)+'%']]
    stats.forEach(([label, value], i) => {
      doc.font('Helvetica-Bold').fontSize(7).fillColor('#5A7A65').text(label, statCols[i], statsY)
      doc.font('Helvetica-Bold').fontSize(16).fillColor('#1A7A50').text(value, statCols[i], statsY + 10)
    })

    doc.y = statsY + 36
    doc.rect(MARGIN, doc.y, CONTENT_W, 1).fill('#D8E4DC')
    doc.moveDown(0.8)

    const cols = [
      { label: 'DATE', x: MARGIN, w: 68 },
      { label: 'START', x: MARGIN+70, w: 42 },
      { label: 'END', x: MARGIN+114, w: 42 },
      { label: 'HRS', x: MARGIN+158, w: 32, align: 'right' },
      { label: 'TYPE', x: MARGIN+196, w: 72 },
      { label: 'SETTING', x: MARGIN+274, w: 72 },
      { label: 'TASK AREA', x: MARGIN+352, w: 72 },
      { label: 'ACTIVITY', x: MARGIN+430, w: 200 },
      { label: 'SUPV', x: MARGIN+636, w: 36, align: 'center' },
    ]

    const tableTop = doc.y
    doc.rect(MARGIN, tableTop, CONTENT_W, 18).fill('#F0F4F1')
    cols.forEach(col => {
      doc.font('Helvetica-Bold').fontSize(7).fillColor('#5A7A65')
        .text(col.label, col.x + 4, tableTop + 5, { width: col.w - 4, align: (col.align || 'left') })
    })
    doc.y = tableTop + 20

    if (entries.length === 0) {
      doc.font('Helvetica').fontSize(10).fillColor('#5A7A65').text('No entries found for this period.', MARGIN, doc.y + 10)
    } else {
      entries.forEach((entry, idx) => {
        if (doc.y > doc.page.height - 120) {
          doc.addPage()
          doc.y = MARGIN
          doc.rect(MARGIN, doc.y, CONTENT_W, 18).fill('#F0F4F1')
          cols.forEach(col => {
            doc.font('Helvetica-Bold').fontSize(7).fillColor('#5A7A65')
              .text(col.label, col.x + 4, doc.y + 5, { width: col.w - 4, align: (col.align || 'left') })
          })
          doc.y += 20
        }
        const rowY = doc.y
        doc.rect(MARGIN, rowY, CONTENT_W, 18).fill(idx % 2 === 0 ? '#FFFFFF' : '#F7FAF8')
        const dateStr = entry.entry_date ? new Date(entry.entry_date).toLocaleDateString('en-US', { month: '2-digit', day: '2-digit', year: '2-digit' }) : '—'
        const taskStr = entry.task_list_area ? `${entry.task_list_area}${entry.task_list_area_number ? '-'+entry.task_list_area_number : ''}` : '—'
        const activityStr = entry.activity_description ? entry.activity_description.slice(0, 60) + (entry.activity_description.length > 60 ? '…' : '') : '—'
        doc.font('Helvetica').fontSize(8).fillColor('#0F2018')
        doc.text(dateStr, cols[0].x+4, rowY+5, { width: cols[0].w })
        doc.text(entry.start_time ? entry.start_time.slice(0,5) : '—', cols[1].x+4, rowY+5, { width: cols[1].w })
        doc.text(entry.end_time ? entry.end_time.slice(0,5) : '—', cols[2].x+4, rowY+5, { width: cols[2].w })
        doc.text(parseFloat(entry.hours||0).toFixed(1), cols[3].x, rowY+5, { width: cols[3].w, align: 'right' })
        doc.text(entry.experience_type || '—', cols[4].x+4, rowY+5, { width: cols[4].w })
        doc.text(entry.setting || '—', cols[5].x+4, rowY+5, { width: cols[5].w })
        doc.text(taskStr, cols[6].x+4, rowY+5, { width: cols[6].w })
        doc.text(activityStr, cols[7].x+4, rowY+5, { width: cols[7].w })
        doc.font('Helvetica-Bold').fontSize(8).fillColor(entry.supervised ? '#1A7A50' : '#9AB5A5')
        doc.text(entry.supervised ? 'Y' : '—', cols[8].x, rowY+5, { width: cols[8].w, align: 'center' })
        doc.y = rowY + 20
      })
    }

    doc.rect(MARGIN, doc.y, CONTENT_W, 1).fill('#D8E4DC')
    doc.moveDown(1.5)

    const sigY = doc.y
    doc.font('Helvetica-Bold').fontSize(8).fillColor('#5A7A65').text('TRAINEE SIGNATURE', MARGIN, sigY)
    if (signature) {
      const sigBuffer = Buffer.from(signature.split(',')[1], 'base64')
      doc.image(sigBuffer, MARGIN, sigY + 16, { width: 160, height: 40 })
    }
    doc.rect(MARGIN, sigY+14, 260, 1).fill('#0F2018')
    doc.font('Helvetica').fontSize(8).fillColor('#5A7A65').text(pro.full_name || '', MARGIN, sigY+18)
    doc.font('Helvetica').fontSize(8).fillColor('#9AB5A5').text('Date: ___________________', MARGIN, sigY+30)
    doc.font('Helvetica-Bold').fontSize(8).fillColor('#5A7A65').text('SUPERVISOR SIGNATURE', MARGIN+340, sigY)
    doc.rect(MARGIN+340, sigY+14, 260, 1).fill('#0F2018')
    doc.font('Helvetica').fontSize(8).fillColor('#9AB5A5').text('Supervisor Name: ________________________', MARGIN+340, sigY+18)
    doc.font('Helvetica').fontSize(8).fillColor('#9AB5A5').text('BACB Cert #: _____________   Date: _____________', MARGIN+340, sigY+30)

    doc.font('Helvetica').fontSize(7).fillColor('#9AB5A5')
      .text(`Generated by Supervisd · ${entries.length} entries · ${totalHours.toFixed(1)} total hours · ${monthLabel}`, MARGIN, doc.page.height - 30, { width: CONTENT_W, align: 'center' })

    doc.end()
  } catch (err) {
    console.error('GET /export error:', err)
    if (!res.headersSent) res.status(500).json({ error: 'Failed to generate PDF' })
  }
})

export default router
